spring:
    application:
        name: messagebroker
    profiles:
        active: dev
            

server:
  port: 8081

logging:
  level: 
    '[com.broker]': debug

redis-servers:
  redisConfigs:
  - name: server
    host: 192.168.0.13
    port: 6379
    password: MyRedis
    maxIdle: 5
    maxTotal: 5 

