spring:
    application:
        name: messagebroker
    profiles:
        active: dev

    datasource:
      url: jdbc:mysql://localhost:3306/dev       # JDBC URL with your database name
      username: devuser                         # Database username
      password: Dev@12321                       # Database password
      driver-class-name: com.mysql.cj.jdbc.Driver

    # jpa:
      # show-sql: true                             # Show SQL queries in logs
      # properties:
        # hibernate:
          # format_sql: true
              

server:
  port: 8081

logging:
  level: 
    '[com.broker]': debug

redis-servers:
  redisConfigs:
  - name: server
    host: 192.168.0.13
    port: 6379
    password: MyRedis
    maxIdle: 5
    maxTotal: 5 


queues:
  producers:
  - queue: BigMailQueue
    server: server
    messageSerializer: DefaultMessageSerializer
    filter: MessageSizeFilter
    filterCriteria: GE 10

  - queue: SmallMailQueue
    server: server
    messageSerializer: DefaultMessageSerializer
    filter: MessageSizeFilter
    filterCriteria: LT 10

