<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.broker</groupId>
  <artifactId>redis-message-broker</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <parent>
  <groupId>com.broker</groupId>
    <artifactId>root</artifactId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>

  <name>redis-message-broker</name>
 


  <dependencies>

    <dependency>
       <groupId>com.broker</groupId>
      <artifactId>message-broker</artifactId>
      <version>0.0.1-SNAPSHOT</version>
    </dependency>

		<dependency>
			<groupId>redis.clients</groupId>
			<artifactId>jedis</artifactId>
			<version>6.0.0</version>
		</dependency>

    <dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-redis</artifactId>
		</dependency>

  </dependencies>

  </project>
